### PR TITLE
Relative paths used in splitter, adds pandas to requirements

### PR DESCRIPTION
**Pull request by mlomnitz**
- [ ] Tests added / passed
- [x] Associated doc strings if new function
- [x] Passes `flake8`

### CODE REVIEW

**Comment by mlomnitz** [comment]
This pull request incorporates the needed changes for splitting. I will push the default splits in a separate pull request

**Comment by zhampel** [comment]
Hey @mlomnitz can you also add in 'tqdm' to the requirements as well por favor?

**Comment by zhampel** [comment]
After `pip install tdqm`, I also get an error from the libri_dataset.py import of soundfile:

    `raise OSError('sndfile library not found')`

Not sure what's causing this, as soundfile is part of the reqs file.

**Comment by zhampel** [comment]
Determined cause of `soundfile` import error. On the CentOS machine, a separate `sudo yum install libsndfile` is required prior to `pip install soundfile`. Appropriate apt-get install calls would be required for other Linux flavors.

**Comment by mlomnitz** [comment]
@zhampel  I have added tqdm to the requirements, please review again

**Comment by mlomnitz** [comment]
@MaAleBarr I have incorporated the requested changes, please review again.

**Pull request merged**
