### PR TITLE
Updates ml-leaks 1 attack: removes redudntant variable

### PR DESCRIPTION
**Pull request by mlomnitz**
- [ ] Tests added / passed
- [ ] Associated doc strings if new function
- [x] Passes `flake8`

### CODE REVIEW

**Comment by zhampel** [comment]
Thanks for the notification. Will re-review.

**Comment by zhampel** [comment]
@mlomnitz can you please run flake8 after yesterday's three additional commits? By eye I see a few lines that can be reformatted.

**Comment by zhampel** [comment]
Otherwise, I approve the PR.

**Comment by MaAleBarr** [comment]
This looks good. I think we are at a good point in build to test through API and start setting examples.

**Pull request merged**
